name: Generate and Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'docker/**/Dockerfile'
      - '.github/workflows/generate-and-push-docker.yml'
  workflow_dispatch:


jobs:
  detect:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Detect Changed Dockerfiles
        id: changed
        uses: tj-actions/changed-files@v47
        with:
          files: |
            docker/**/Dockerfile

      - name: Generate Build Matrix
        id: detect
        run: |
          FILES='${{ steps.changed.outputs.all_changed_files }}'

          # Initialize an empty array for the matrix
          MATRIX=()
          # Loop through the changed files and extract target, image, and dockerfile path
          for FILE in $FILES; do
            if [[ $FILE == docker/*/Dockerfile ]]; then
              TARGET=$(echo $FILE | cut -d'/' -f2)
              IMAGE="liara-engine/${TARGET}"
              DOCKERFILE_PATH=$FILE
              MATRIX+=("{\"target\":\"$TARGET\", \"image\":\"$IMAGE\", \"dockerfile\":\"$DOCKERFILE_PATH\"}")
            fi
          done
          
          # Convert the array to a JSON string
          JSON=$(printf '%s\n' "${MATRIX[@]}" | jq -cs '.')

          echo "matrix={\"include\":$JSON}" >> $GITHUB_OUTPUT
          
          # Debug output
          echo "Generated matrix: $JSON"

  build:
    needs: detect
    if: needs.detect.outputs.matrix != '[]'

    permissions:
      contents: read
      packages: write

    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}

    uses: liara-engine/.github/.github/workflows/reusable-generate-docker.yml@v0

    with:
      target: ${{ matrix.target }}
      image-name: ${{ matrix.image }}
      image-tag: ${{ github.ref_name }}
      dockerfile-path: ${{ matrix.dockerfile }}